"""Tests for the GitAdapter subprocess wrapper."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Callable
from unittest.mock import MagicMock, patch

import pytest

from turma.errors import PlanningError
from turma.swarm.git import (
    COMMIT_MESSAGE_TEMPLATE,
    GIT_INSTALL_HINT,
    GitAdapter,
)


def _completed(
    argv: list[str], stdout: str = "", stderr: str = "", code: int = 0
) -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess(argv, code, stdout=stdout, stderr=stderr)


def _make_adapter_with_run(
    run_fn: Callable[..., subprocess.CompletedProcess[str]],
) -> GitAdapter:
    with patch(
        "turma.swarm.git.shutil.which", return_value="/usr/bin/git"
    ):
        adapter = GitAdapter()
    adapter._run = run_fn  # type: ignore[method-assign]
    return adapter


# ---------------------------------------------------------------------
# Construction
# ---------------------------------------------------------------------


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
def test_init_succeeds_when_git_on_path(_which: MagicMock) -> None:
    GitAdapter()  # no exception


@patch("turma.swarm.git.shutil.which", return_value=None)
def test_init_raises_when_git_missing(_which: MagicMock) -> None:
    with pytest.raises(PlanningError) as exc:
        GitAdapter()
    assert str(exc.value) == GIT_INSTALL_HINT


# ---------------------------------------------------------------------
# Commit message template
# ---------------------------------------------------------------------


def test_commit_template_uses_task_id_without_bd_prefix() -> None:
    # Prior spec drafts had `Closes bd-{task_id}.` which would render
    # `Closes bd-bd-smoke-1.`. The template uses `{task_id}` verbatim
    # and expects the caller to pass the full bd id.
    assert "Closes bd-" not in COMMIT_MESSAGE_TEMPLATE
    assert "Closes {task_id}." in COMMIT_MESSAGE_TEMPLATE


def test_commit_template_renders_as_expected() -> None:
    rendered = COMMIT_MESSAGE_TEMPLATE.format(
        turma_type="impl",
        task_title="Extract planner primitives",
        task_id="bd-smoke-1",
        feature="oauth",
    )
    assert rendered == (
        "[impl] Extract planner primitives\n"
        "\n"
        "Closes bd-smoke-1.\n"
        "\n"
        'Generated by turma run for feature "oauth".'
    )


# ---------------------------------------------------------------------
# status_is_dirty
# ---------------------------------------------------------------------


def test_status_is_dirty_true_when_porcelain_output_non_empty(
    tmp_path: Path,
) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        return _completed(argv, stdout=" M src/turma/foo.py\n")

    adapter = _make_adapter_with_run(run)
    assert adapter.status_is_dirty(tmp_path) is True
    assert seen == [
        ["git", "-C", str(tmp_path), "status", "--porcelain=v1"]
    ]


def test_status_is_dirty_false_when_porcelain_output_empty(
    tmp_path: Path,
) -> None:
    adapter = _make_adapter_with_run(
        lambda argv, *, step: _completed(argv, stdout="")
    )
    assert adapter.status_is_dirty(tmp_path) is False


def test_status_is_dirty_false_when_only_whitespace(
    tmp_path: Path,
) -> None:
    adapter = _make_adapter_with_run(
        lambda argv, *, step: _completed(argv, stdout="\n   \n")
    )
    assert adapter.status_is_dirty(tmp_path) is False


# ---------------------------------------------------------------------
# commit_all
# ---------------------------------------------------------------------


def test_commit_all_pins_argv_and_returns_sha(tmp_path: Path) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout=" M file.py\n")
        if argv[3:5] == ["add", "-A"]:
            return _completed(argv)
        if argv[3:5] == ["commit", "-m"]:
            return _completed(argv)
        if argv[3:5] == ["rev-parse", "HEAD"]:
            return _completed(argv, stdout="deadbeefcafef00d\n")
        raise AssertionError(f"unexpected argv: {argv}")

    adapter = _make_adapter_with_run(run)
    sha = adapter.commit_all(tmp_path, "commit message body")

    assert sha == "deadbeefcafef00d"
    # Order: status → add → commit → rev-parse.
    assert [a[3:5] for a in seen] == [
        ["status", "--porcelain=v1"],
        ["add", "-A"],
        ["commit", "-m"],
        ["rev-parse", "HEAD"],
    ]
    # commit argv passes the message as the flag's value.
    commit_argv = next(
        a for a in seen if a[3:5] == ["commit", "-m"]
    )
    assert commit_argv == [
        "git", "-C", str(tmp_path),
        "commit", "-m", "commit message body",
    ]


def test_commit_all_refuses_empty_commit(tmp_path: Path) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout="")  # clean tree
        raise AssertionError(
            f"commit_all must not proceed past status on a clean tree: {argv}"
        )

    adapter = _make_adapter_with_run(run)
    with pytest.raises(PlanningError, match="nothing to commit"):
        adapter.commit_all(tmp_path, "message")

    assert [a[3:5] for a in seen] == [["status", "--porcelain=v1"]]


def test_commit_all_raises_when_rev_parse_returns_empty(
    tmp_path: Path,
) -> None:
    def run(argv, *, step):
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout=" M x\n")
        if argv[3:5] == ["rev-parse", "HEAD"]:
            return _completed(argv, stdout="")
        return _completed(argv)

    adapter = _make_adapter_with_run(run)
    with pytest.raises(PlanningError, match="rev-parse HEAD returned empty"):
        adapter.commit_all(tmp_path, "message")


# ---------------------------------------------------------------------
# push_branch
# ---------------------------------------------------------------------


def test_push_branch_pins_argv_with_default_remote(tmp_path: Path) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        return _completed(argv)

    adapter = _make_adapter_with_run(run)
    adapter.push_branch(tmp_path, "task/oauth/bd-smoke-1")

    assert seen == [
        [
            "git", "-C", str(tmp_path),
            "push", "--set-upstream", "origin", "task/oauth/bd-smoke-1",
        ]
    ]


def test_push_branch_accepts_custom_remote(tmp_path: Path) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        return _completed(argv)

    adapter = _make_adapter_with_run(run)
    adapter.push_branch(
        tmp_path, "task/oauth/bd-1", remote="upstream"
    )

    assert seen[0][3:] == [
        "push", "--set-upstream", "upstream", "task/oauth/bd-1",
    ]


# ---------------------------------------------------------------------
# _run plumbing
# ---------------------------------------------------------------------


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_run_surfaces_stderr_on_non_zero_exit(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """An auth failure on push surfaces git's stderr verbatim."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=["git", "push"],
        returncode=128,
        stdout="",
        stderr=(
            "fatal: Authentication failed for "
            "'https://github.com/turma-dev/turma'"
        ),
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError) as exc:
        adapter.push_branch(tmp_path, "task/oauth/bd-1")
    msg = str(exc.value)
    assert "git push failed" in msg
    assert "Authentication failed" in msg


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_run_falls_back_to_stdout_when_stderr_empty(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    mock_run.return_value = subprocess.CompletedProcess(
        args=["git", "status"],
        returncode=1,
        stdout="fatal: not a git repository",
        stderr="",
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError, match="not a git repository"):
        adapter.status_is_dirty(tmp_path)


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_run_falls_back_to_unknown_error_when_both_empty(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    mock_run.return_value = subprocess.CompletedProcess(
        args=["git", "status"],
        returncode=1,
        stdout="",
        stderr="",
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError, match="unknown error"):
        adapter.status_is_dirty(tmp_path)


# ---------------------------------------------------------------------
# Integration: commit_all surfaces a commit-level failure
# ---------------------------------------------------------------------


def test_commit_all_surfaces_commit_subprocess_failure(
    tmp_path: Path,
) -> None:
    """A failing `git commit` (e.g. pre-commit hook rejection) surfaces stderr."""
    def run(argv, *, step):
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout=" M file\n")
        if argv[3:5] == ["add", "-A"]:
            return _completed(argv)
        if argv[3:5] == ["commit", "-m"]:
            raise PlanningError(
                "git commit failed: exit 1\n"
                "pre-commit: tests failed"
            )
        raise AssertionError(f"unexpected argv: {argv}")

    adapter = _make_adapter_with_run(run)
    with pytest.raises(PlanningError, match="pre-commit: tests failed"):
        adapter.commit_all(tmp_path, "message")


# ---------------------------------------------------------------------
# fetch_and_ff_base (swarm-merge-advancement-stabilization Task 3)
# ---------------------------------------------------------------------


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_pins_argv_shape(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Single-call colon-form fetch:
    `git -C <repo_root> fetch origin <base>:<base>`.

    The colon-form refspec fetches `origin/<base>` and fast-forwards
    local `<base>` to match in one operation. No separate
    `git merge --ff-only` step.
    """
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="", stderr=""
    )
    adapter = GitAdapter()
    adapter.fetch_and_ff_base(tmp_path, "main")

    mock_run.assert_called_once()
    actual_argv = mock_run.call_args.args[0]
    assert actual_argv == [
        "git", "-C", str(tmp_path),
        "fetch", "origin", "main:main",
    ]


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_happy_path_returns_none(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Zero exit → method returns None (no payload). The colon-form
    is silent on success; reading the up-to-date / advanced state
    from stdout/stderr is cosmetic and not part of the contract."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0,
        stdout="",
        stderr="From github.com:turma-dev/turma\n   abc..def  main → main\n",
    )
    adapter = GitAdapter()
    assert adapter.fetch_and_ff_base(tmp_path, "main") is None


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_typed_error_on_non_fast_forward(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Local `<base>` has diverged from origin → typed PlanningError
    naming the branch and pointing the operator at the two
    `git log` commands needed to compare divergence directions.
    Pin the substring `non-fast-forward` triggers this branch."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=1,
        stdout="",
        stderr=(
            "From github.com:turma-dev/turma\n"
            " ! [rejected]        main -> main (non-fast-forward)\n"
        ),
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "main")
    msg = str(exc.value)
    assert "main" in msg
    assert "diverged" in msg.lower()
    # Both triage directions named so the operator can compare.
    assert "main..origin/main" in msg
    assert "origin/main..main" in msg


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_typed_error_on_rejected_substring(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Some divergence-rejection messages from older git versions
    use `! [rejected]` without the explicit `non-fast-forward`
    parenthetical. Pin that the typed-error branch fires on
    `[rejected]` too."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=1,
        stdout="",
        stderr=(
            "From github.com:turma-dev/turma\n"
            " ! [rejected]        main -> main\n"
        ),
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "main")
    msg = str(exc.value)
    assert "diverged" in msg.lower()


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_generic_error_preserves_stderr(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Network / auth failures (anything that isn't a
    non-fast-forward / rejected signal) surface as PlanningError
    with stderr preserved verbatim and a `git fetch failed:`
    prefix so the operator can grep the run log."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=128,
        stdout="",
        stderr=(
            "fatal: Could not read from remote repository.\n"
            "Please make sure you have the correct access rights\n"
            "and the repository exists.\n"
        ),
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "main")
    msg = str(exc.value)
    assert "git fetch failed" in msg
    assert "Could not read from remote" in msg
    # Should NOT mention the diverged-triage hint for a non-divergence
    # failure.
    assert "main..origin/main" not in msg


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_branch_name_interpolated_into_typed_error(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """The typed error uses the supplied `base_branch` parameter,
    not a hard-coded `main`. Operators with a non-default base
    branch (e.g. `develop`) get useful triage commands."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=1,
        stdout="",
        stderr=(
            "From github.com:owner/repo\n"
            " ! [rejected]        develop -> develop (non-fast-forward)\n"
        ),
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "develop")
    msg = str(exc.value)
    assert "develop..origin/develop" in msg
    assert "origin/develop..develop" in msg
    assert "main" not in msg.replace("develop", "")  # no leaked default
