"""Tests for the GitAdapter subprocess wrapper."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Callable
from unittest.mock import MagicMock, patch

import pytest

from turma.errors import PlanningError
from turma.swarm.git import (
    COMMIT_MESSAGE_TEMPLATE,
    GIT_INSTALL_HINT,
    GitAdapter,
)


def _completed(
    argv: list[str], stdout: str = "", stderr: str = "", code: int = 0
) -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess(argv, code, stdout=stdout, stderr=stderr)


def _make_adapter_with_run(
    run_fn: Callable[..., subprocess.CompletedProcess[str]],
) -> GitAdapter:
    with patch(
        "turma.swarm.git.shutil.which", return_value="/usr/bin/git"
    ):
        adapter = GitAdapter()
    adapter._run = run_fn  # type: ignore[method-assign]
    return adapter


# ---------------------------------------------------------------------
# Construction
# ---------------------------------------------------------------------


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
def test_init_succeeds_when_git_on_path(_which: MagicMock) -> None:
    GitAdapter()  # no exception


@patch("turma.swarm.git.shutil.which", return_value=None)
def test_init_raises_when_git_missing(_which: MagicMock) -> None:
    with pytest.raises(PlanningError) as exc:
        GitAdapter()
    assert str(exc.value) == GIT_INSTALL_HINT


# ---------------------------------------------------------------------
# Commit message template
# ---------------------------------------------------------------------


def test_commit_template_uses_task_id_without_bd_prefix() -> None:
    # Prior spec drafts had `Closes bd-{task_id}.` which would render
    # `Closes bd-bd-smoke-1.`. The template uses `{task_id}` verbatim
    # and expects the caller to pass the full bd id.
    assert "Closes bd-" not in COMMIT_MESSAGE_TEMPLATE
    assert "Closes {task_id}." in COMMIT_MESSAGE_TEMPLATE


def test_commit_template_renders_as_expected() -> None:
    rendered = COMMIT_MESSAGE_TEMPLATE.format(
        turma_type="impl",
        task_title="Extract planner primitives",
        task_id="bd-smoke-1",
        feature="oauth",
    )
    assert rendered == (
        "[impl] Extract planner primitives\n"
        "\n"
        "Closes bd-smoke-1.\n"
        "\n"
        'Generated by turma run for feature "oauth".'
    )


# ---------------------------------------------------------------------
# status_is_dirty
# ---------------------------------------------------------------------


def test_status_is_dirty_true_when_porcelain_output_non_empty(
    tmp_path: Path,
) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        return _completed(argv, stdout=" M src/turma/foo.py\n")

    adapter = _make_adapter_with_run(run)
    assert adapter.status_is_dirty(tmp_path) is True
    assert seen == [
        ["git", "-C", str(tmp_path), "status", "--porcelain=v1"]
    ]


def test_status_is_dirty_false_when_porcelain_output_empty(
    tmp_path: Path,
) -> None:
    adapter = _make_adapter_with_run(
        lambda argv, *, step: _completed(argv, stdout="")
    )
    assert adapter.status_is_dirty(tmp_path) is False


def test_status_is_dirty_false_when_only_whitespace(
    tmp_path: Path,
) -> None:
    adapter = _make_adapter_with_run(
        lambda argv, *, step: _completed(argv, stdout="\n   \n")
    )
    assert adapter.status_is_dirty(tmp_path) is False


def test_status_is_dirty_ignore_bd_export_excludes_the_export(
    tmp_path: Path,
) -> None:
    """`ignore_bd_export=True` adds the `:!.beads/issues.jsonl` pathspec so the
    dirtiness check matches the code-only staged set — a worktree dirty only in
    the bd export reads as clean (swarm-bd-export-serialization). The default
    stays broad."""
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        return _completed(argv, stdout="")

    adapter = _make_adapter_with_run(run)

    adapter.status_is_dirty(tmp_path, ignore_bd_export=True)
    assert seen[-1][-3:] == ["--", ".", ":!.beads/issues.jsonl"]

    adapter.status_is_dirty(tmp_path)  # default: broad, no pathspec
    assert "--" not in seen[-1]


# ---------------------------------------------------------------------
# commit_all
# ---------------------------------------------------------------------


def test_commit_all_pins_argv_and_returns_sha(tmp_path: Path) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout=" M file.py\n")
        if argv[3:5] == ["add", "-A"]:
            return _completed(argv)
        if argv[3:5] == ["commit", "-m"]:
            return _completed(argv)
        if argv[3:5] == ["rev-parse", "HEAD"]:
            return _completed(argv, stdout="deadbeefcafef00d\n")
        raise AssertionError(f"unexpected argv: {argv}")

    adapter = _make_adapter_with_run(run)
    sha = adapter.commit_all(tmp_path, "commit message body")

    assert sha == "deadbeefcafef00d"
    # Order: status → add → commit → rev-parse.
    assert [a[3:5] for a in seen] == [
        ["status", "--porcelain=v1"],
        ["add", "-A"],
        ["commit", "-m"],
        ["rev-parse", "HEAD"],
    ]
    # commit argv passes the message as the flag's value.
    commit_argv = next(
        a for a in seen if a[3:5] == ["commit", "-m"]
    )
    assert commit_argv == [
        "git", "-C", str(tmp_path),
        "commit", "-m", "commit message body",
    ]


def test_commit_all_refuses_empty_commit(tmp_path: Path) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout="")  # clean tree
        raise AssertionError(
            f"commit_all must not proceed past status on a clean tree: {argv}"
        )

    adapter = _make_adapter_with_run(run)
    with pytest.raises(PlanningError, match="nothing to commit"):
        adapter.commit_all(tmp_path, "message")

    assert [a[3:5] for a in seen] == [["status", "--porcelain=v1"]]


def test_commit_all_raises_when_rev_parse_returns_empty(
    tmp_path: Path,
) -> None:
    def run(argv, *, step):
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout=" M x\n")
        if argv[3:5] == ["rev-parse", "HEAD"]:
            return _completed(argv, stdout="")
        return _completed(argv)

    adapter = _make_adapter_with_run(run)
    with pytest.raises(PlanningError, match="rev-parse HEAD returned empty"):
        adapter.commit_all(tmp_path, "message")


# ---------------------------------------------------------------------
# push_branch
# ---------------------------------------------------------------------


def test_push_branch_pins_argv_with_default_remote(tmp_path: Path) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        return _completed(argv)

    adapter = _make_adapter_with_run(run)
    adapter.push_branch(tmp_path, "task/oauth/bd-smoke-1")

    assert seen == [
        [
            "git", "-C", str(tmp_path),
            "push", "--set-upstream", "origin", "task/oauth/bd-smoke-1",
        ]
    ]


def test_push_branch_accepts_custom_remote(tmp_path: Path) -> None:
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        return _completed(argv)

    adapter = _make_adapter_with_run(run)
    adapter.push_branch(
        tmp_path, "task/oauth/bd-1", remote="upstream"
    )

    assert seen[0][3:] == [
        "push", "--set-upstream", "upstream", "task/oauth/bd-1",
    ]


# ---------------------------------------------------------------------
# _run plumbing
# ---------------------------------------------------------------------


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_run_surfaces_stderr_on_non_zero_exit(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """An auth failure on push surfaces git's stderr verbatim."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=["git", "push"],
        returncode=128,
        stdout="",
        stderr=(
            "fatal: Authentication failed for "
            "'https://github.com/turma-dev/turma'"
        ),
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError) as exc:
        adapter.push_branch(tmp_path, "task/oauth/bd-1")
    msg = str(exc.value)
    assert "git push failed" in msg
    assert "Authentication failed" in msg


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_run_falls_back_to_stdout_when_stderr_empty(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    mock_run.return_value = subprocess.CompletedProcess(
        args=["git", "status"],
        returncode=1,
        stdout="fatal: not a git repository",
        stderr="",
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError, match="not a git repository"):
        adapter.status_is_dirty(tmp_path)


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_run_falls_back_to_unknown_error_when_both_empty(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    mock_run.return_value = subprocess.CompletedProcess(
        args=["git", "status"],
        returncode=1,
        stdout="",
        stderr="",
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError, match="unknown error"):
        adapter.status_is_dirty(tmp_path)


# ---------------------------------------------------------------------
# Integration: commit_all surfaces a commit-level failure
# ---------------------------------------------------------------------


def test_commit_all_surfaces_commit_subprocess_failure(
    tmp_path: Path,
) -> None:
    """A failing `git commit` (e.g. pre-commit hook rejection) surfaces stderr."""
    def run(argv, *, step):
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout=" M file\n")
        if argv[3:5] == ["add", "-A"]:
            return _completed(argv)
        if argv[3:5] == ["commit", "-m"]:
            raise PlanningError(
                "git commit failed: exit 1\n"
                "pre-commit: tests failed"
            )
        raise AssertionError(f"unexpected argv: {argv}")

    adapter = _make_adapter_with_run(run)
    with pytest.raises(PlanningError, match="pre-commit: tests failed"):
        adapter.commit_all(tmp_path, "message")


# ---------------------------------------------------------------------
# fetch_and_ff_base
# (swarm-fetch-and-ff-base-correction supersedes the colon-form
# from swarm-merge-advancement-stabilization Task 3)
# ---------------------------------------------------------------------


def _ok(stdout: str = "", stderr: str = "") -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess(
        args=[], returncode=0, stdout=stdout, stderr=stderr
    )


def _fail(
    code: int, stderr: str = "", stdout: str = ""
) -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess(
        args=[], returncode=code, stdout=stdout, stderr=stderr
    )


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_pins_argv_shape(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Three subprocess calls in order: symbolic-ref → fetch → merge.

    See `openspec/changes/swarm-fetch-and-ff-base-correction/`
    for the contract. The HEAD precheck guards the silent
    feature-FF footgun the colon-form ignored.
    """
    # symbolic-ref returns the current branch name on stdout.
    mock_run.side_effect = [
        _ok(stdout="main\n"),  # symbolic-ref
        _ok(),                 # fetch
        _ok(),                 # merge
    ]
    adapter = GitAdapter()
    adapter.fetch_and_ff_base(tmp_path, "main")

    assert mock_run.call_count == 3
    argv_calls = [c.args[0] for c in mock_run.call_args_list]
    assert argv_calls == [
        ["git", "-C", str(tmp_path), "symbolic-ref", "--short", "HEAD"],
        ["git", "-C", str(tmp_path), "fetch", "origin", "main"],
        ["git", "-C", str(tmp_path),
         "merge", "--ff-only", "origin/main"],
    ]


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_happy_path_returns_none(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """All three calls return zero exit; method returns None."""
    mock_run.side_effect = [
        _ok(stdout="main\n"),
        _ok(stderr="From github.com:owner/repo\n   abc..def  main → main\n"),
        _ok(stdout="Updating abc..def\nFast-forward\n"),
    ]
    adapter = GitAdapter()
    assert adapter.fetch_and_ff_base(tmp_path, "main") is None


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_typed_error_on_head_not_on_base(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """symbolic-ref returns a branch name that isn't `<base_branch>`
    → typed PlanningError pointing operator at `cd`. Fetch + merge
    must NOT be invoked. This is the silent-feature-FF footgun
    the precheck closes."""
    mock_run.side_effect = [_ok(stdout="feature-x\n")]
    adapter = GitAdapter()

    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "main")

    # Exactly ONE call (the precheck). Fetch + merge skipped.
    assert mock_run.call_count == 1
    msg = str(exc.value)
    assert "feature-x" in msg
    assert "main" in msg
    assert "cd" in msg.lower()


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_typed_error_on_detached_head(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """symbolic-ref non-zero exit (e.g. detached HEAD) → typed
    PlanningError with the detached-HEAD signal preserved. Fetch
    + merge must NOT be invoked."""
    mock_run.side_effect = [
        _fail(128, stderr="fatal: ref HEAD is not a symbolic ref\n"),
    ]
    adapter = GitAdapter()

    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "main")

    assert mock_run.call_count == 1
    msg = str(exc.value)
    assert "detached" in msg.lower()
    assert "main" in msg


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_skips_merge_when_fetch_fails(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """symbolic-ref ok; fetch raises non-zero → exactly TWO calls
    (precheck + fetch). Merge is NOT invoked. Pin the ordering."""
    mock_run.side_effect = [
        _ok(stdout="main\n"),
        _fail(
            128,
            stderr=(
                "fatal: Could not read from remote repository.\n"
                "Please make sure you have the correct access rights\n"
                "and the repository exists.\n"
            ),
        ),
    ]
    adapter = GitAdapter()

    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "main")

    assert mock_run.call_count == 2
    msg = str(exc.value)
    assert "git fetch failed" in msg
    assert "Could not read from remote" in msg
    # No diverged-triage hint for a fetch failure.
    assert "main..origin/main" not in msg


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_typed_error_on_non_fast_forward(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """symbolic-ref + fetch ok; merge returns non-zero with
    `Not possible to fast-forward` in stderr → typed divergence
    error naming the branch and pointing at both
    `git log <a>..<b>` triage commands."""
    mock_run.side_effect = [
        _ok(stdout="main\n"),
        _ok(),
        _fail(
            1,
            stderr=(
                "fatal: Not possible to fast-forward, aborting.\n"
            ),
        ),
    ]
    adapter = GitAdapter()

    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "main")

    assert mock_run.call_count == 3
    msg = str(exc.value)
    assert "diverged" in msg.lower()
    assert "main..origin/main" in msg
    assert "origin/main..main" in msg


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_merge_generic_failure_preserves_stderr(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Merge non-zero with stderr that doesn't match the
    divergence signal → generic `git merge --ff-only failed:`
    PlanningError preserving stderr."""
    mock_run.side_effect = [
        _ok(stdout="main\n"),
        _ok(),
        _fail(1, stderr="some unexpected merge error\n"),
    ]
    adapter = GitAdapter()

    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "main")

    msg = str(exc.value)
    assert "git merge --ff-only failed" in msg
    assert "some unexpected merge error" in msg
    # No diverged-triage hint for a generic merge failure.
    assert "main..origin/main" not in msg


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_fetch_and_ff_base_branch_name_interpolated_into_typed_error(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """The typed error uses the supplied `base_branch` parameter,
    not a hard-coded `main`. Operators with a non-default base
    branch (e.g. `develop`) get useful triage commands."""
    mock_run.side_effect = [
        _ok(stdout="develop\n"),
        _ok(),
        _fail(1, stderr="fatal: Not possible to fast-forward, aborting.\n"),
    ]
    adapter = GitAdapter()

    with pytest.raises(PlanningError) as exc:
        adapter.fetch_and_ff_base(tmp_path, "develop")

    msg = str(exc.value)
    assert "develop..origin/develop" in msg
    assert "origin/develop..develop" in msg
    # No leaked default `main` outside the `develop` substitutions.
    assert "main" not in msg.replace("develop", "")


# ---------------------------------------------------------------------
# revert_paths + path_is_dirty
# (swarm-beads-state-merge-cleanliness Task 1)
# ---------------------------------------------------------------------


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_revert_paths_pins_argv_shape(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """`git -C <repo_root> restore --staged --worktree -- <p1> ...`.

    Both `--staged` and `--worktree` because bd's
    `export.git-add=true` (default) means `bd update` writes
    AND stages `.beads/issues.jsonl`. A simple
    `git checkout -- <path>` would only fix the worktree;
    `restore --staged --worktree` clears both.
    """
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="", stderr=""
    )
    adapter = GitAdapter()
    adapter.revert_paths(tmp_path, (".beads/issues.jsonl",))

    mock_run.assert_called_once()
    actual_argv = mock_run.call_args.args[0]
    assert actual_argv == [
        "git", "-C", str(tmp_path),
        "restore", "--staged", "--worktree",
        "--", ".beads/issues.jsonl",
    ]


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_revert_paths_empty_paths_skips_subprocess(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Empty paths tuple → no subprocess call. Don't fire git
    with zero paths; its defaults are surprising and we don't
    want operator confusion if a future call site accidentally
    passes ()."""
    adapter = GitAdapter()
    result = adapter.revert_paths(tmp_path, ())

    assert result is None
    assert mock_run.call_count == 0


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_revert_paths_multi_path_pins_argv_order(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Paths are passed verbatim in order after `--`.
    Stable order pins the operator-facing log if/when git
    fails."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="", stderr=""
    )
    adapter = GitAdapter()
    adapter.revert_paths(
        tmp_path, (".beads/issues.jsonl", ".beads/config.yaml")
    )

    actual_argv = mock_run.call_args.args[0]
    assert actual_argv == [
        "git", "-C", str(tmp_path),
        "restore", "--staged", "--worktree",
        "--", ".beads/issues.jsonl", ".beads/config.yaml",
    ]


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_revert_paths_failure_surfaces_stderr(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Non-zero exit → `PlanningError("git restore failed:
    ...", stderr_preserved)`. Possible causes: file doesn't
    exist (operator deleted it), git config issues, file
    isn't tracked. Halts the run; operator triages."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=1,
        stdout="",
        stderr=(
            "error: pathspec '.beads/issues.jsonl' did not "
            "match any files\n"
        ),
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError) as exc:
        adapter.revert_paths(tmp_path, (".beads/issues.jsonl",))
    msg = str(exc.value)
    assert "git restore failed" in msg
    assert "did not match any files" in msg


# path_is_dirty -------------------------------------------------------


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_path_is_dirty_pins_argv_shape(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """`git -C <repo_root> status --porcelain=v1 -- <path>`.
    Used by the preflight check before run_swarm to refuse
    on a pre-existing dirty `.beads/issues.jsonl`."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="", stderr=""
    )
    adapter = GitAdapter()
    adapter.path_is_dirty(tmp_path, ".beads/issues.jsonl")

    mock_run.assert_called_once()
    actual_argv = mock_run.call_args.args[0]
    assert actual_argv == [
        "git", "-C", str(tmp_path),
        "status", "--porcelain=v1", "--", ".beads/issues.jsonl",
    ]


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_path_is_dirty_returns_false_on_clean(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Empty stdout (clean working tree) → False."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="", stderr=""
    )
    adapter = GitAdapter()
    assert adapter.path_is_dirty(tmp_path, ".beads/issues.jsonl") is False


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_path_is_dirty_returns_true_on_modified_unstaged(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Unstaged modification (` M <path>` in porcelain
    output) → True. This is the post-bd-update state when
    `export.git-add=false` is configured."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0,
        stdout=" M .beads/issues.jsonl\n",
        stderr="",
    )
    adapter = GitAdapter()
    assert adapter.path_is_dirty(tmp_path, ".beads/issues.jsonl") is True


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_path_is_dirty_returns_true_on_staged(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Staged modification (`M  <path>` in porcelain output)
    → True. This is the post-bd-update state under bd's
    default `export.git-add=true` config — the case the
    smoke surfaced."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0,
        stdout="M  .beads/issues.jsonl\n",
        stderr="",
    )
    adapter = GitAdapter()
    assert adapter.path_is_dirty(tmp_path, ".beads/issues.jsonl") is True


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_path_is_dirty_returns_false_on_untracked(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Untracked file at the path (`?? <path>` in porcelain
    output) → False. An untracked file at the bd-state path
    is the operator's business, not Turma's; we don't
    refuse to start on it."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=0,
        stdout="?? .beads/issues.jsonl\n",
        stderr="",
    )
    adapter = GitAdapter()
    assert adapter.path_is_dirty(tmp_path, ".beads/issues.jsonl") is False


@patch("turma.swarm.git.shutil.which", return_value="/usr/bin/git")
@patch("turma.swarm.git.subprocess.run")
def test_path_is_dirty_failure_surfaces_stderr(
    mock_run: MagicMock, _which: MagicMock, tmp_path: Path
) -> None:
    """Non-zero exit → `PlanningError("git status failed:
    ...", stderr_preserved)`. Surfaces the actual git error
    to the operator instead of silently treating as
    clean."""
    mock_run.return_value = subprocess.CompletedProcess(
        args=[], returncode=128,
        stdout="",
        stderr="fatal: not a git repository\n",
    )
    adapter = GitAdapter()
    with pytest.raises(PlanningError) as exc:
        adapter.path_is_dirty(tmp_path, ".beads/issues.jsonl")
    msg = str(exc.value)
    assert "git status failed" in msg
    assert "not a git repository" in msg


# ---------------------------------------------------------------------
# commit_worker_changes
# (swarm-bd-export-serialization; supersedes swarm-worker-commit-bd-ownership
#  Task 2 — task commits are code-only, no bd export)
# ---------------------------------------------------------------------


def _commit_message() -> str:
    return "[impl] worker test commit"


def test_commit_worker_changes_pins_full_sequence(
    tmp_path: Path,
) -> None:
    """Happy commit-boundary protocol: status check → git add -A (excluding
    the bd export) → git commit (with hook bypass) → rev-parse. Exact order,
    exact argv, returns the new SHA. No bd export happens — task commits are
    code-only (swarm-bd-export-serialization).

    The hook-bypass flag (`-c core.hooksPath=/dev/null`) is load-bearing:
    removing it lets bd's pre-commit hook re-export and re-stage
    `.beads/issues.jsonl` into the commit.
    """
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout=" M file.py\n")
        if argv[3:5] == ["add", "-A"]:
            return _completed(argv)
        if argv[3:5] == ["reset", "-q"]:
            return _completed(argv)
        if argv[3] == "-c" and argv[5:7] == ["commit", "-m"]:
            return _completed(argv)
        if argv[3:5] == ["rev-parse", "HEAD"]:
            return _completed(argv, stdout="cafebabe1234\n")
        raise AssertionError(f"unexpected argv: {argv}")

    adapter = _make_adapter_with_run(run)
    worktree = tmp_path / "wt"
    worktree.mkdir()

    sha = adapter.commit_worker_changes(worktree, _commit_message())

    assert sha == "cafebabe1234"

    # git calls in order: status → add → unstage export → commit → rev-parse
    # (no bd export).
    assert [a[3:5] for a in seen if a[3:5] != []] == [
        ["status", "--porcelain=v1"],
        ["add", "-A"],
        ["reset", "-q"],
        # commit's argv[3:5] is ["-c", "core.hooksPath=/dev/null"].
        ["-c", "core.hooksPath=/dev/null"],
        ["rev-parse", "HEAD"],
    ]
    # commit's full argv pinned, including the message.
    commit_argv = next(a for a in seen if "commit" in a)
    assert commit_argv == [
        "git", "-C", str(worktree),
        "-c", "core.hooksPath=/dev/null",
        "commit", "-m", _commit_message(),
    ]


def test_commit_worker_changes_unstages_the_bd_export(
    tmp_path: Path,
) -> None:
    """The bd export is kept out of the commit by an explicit un-stage, not a
    plain `git add` pathspec exclude: a pathspec exclude only affects what `add`
    stages, so it cannot remove a `.beads/issues.jsonl` that bd already staged
    (`export.git-add=true`). `git add -A` then `git reset -q --
    .beads/issues.jsonl` drops that path from the index regardless of how it got
    staged (swarm-bd-export-serialization)."""
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout=" M file.py\n")
        if argv[3:5] == ["rev-parse", "HEAD"]:
            return _completed(argv, stdout="abc\n")
        return _completed(argv)

    adapter = _make_adapter_with_run(run)
    worktree = tmp_path / "wt"
    worktree.mkdir()

    adapter.commit_worker_changes(worktree, _commit_message())

    # `add -A` stages everything (no pathspec filter)…
    add_argv = next(a for a in seen if a[3:5] == ["add", "-A"])
    assert add_argv == ["git", "-C", str(worktree), "add", "-A"]
    # …and the export is then explicitly unstaged, before the commit. `git
    # reset` (not `restore --staged`) so an untracked export is a clean no-op.
    reset_argv = next(a for a in seen if a[3:5] == ["reset", "-q"])
    assert reset_argv == [
        "git", "-C", str(worktree),
        "reset", "-q", "--", ".beads/issues.jsonl",
    ]
    idx = [a[3:5] for a in seen]
    assert idx.index(["reset", "-q"]) < next(
        i for i, a in enumerate(idx) if a == ["-c", "core.hooksPath=/dev/null"]
    ), "unstage must run before commit"


def test_commit_worker_changes_empty_commit_guard_excludes_bd_export(
    tmp_path: Path,
) -> None:
    """Empty-commit guard preserved AND consistent with staging: the guard's
    dirtiness check excludes `.beads/issues.jsonl` (same set that gets staged),
    so a worktree dirty ONLY in the bd export reads as clean and refuses to
    commit — instead of passing the guard and then failing `git commit` with
    nothing staged (swarm-bd-export-serialization)."""
    seen: list[list[str]] = []

    def run(argv, *, step):
        seen.append(argv)
        if argv[3:5] == ["status", "--porcelain=v1"]:
            return _completed(argv, stdout="")  # clean after excluding export
        raise AssertionError(
            "must not advance past status on a clean tree: "
            f"{argv}"
        )

    adapter = _make_adapter_with_run(run)
    worktree = tmp_path / "wt"
    worktree.mkdir()

    with pytest.raises(PlanningError, match="nothing to commit"):
        adapter.commit_worker_changes(worktree, _commit_message())

    # Only status ran (no add/commit/rev-parse), and it carried the exclusion.
    assert [a[3:5] for a in seen] == [["status", "--porcelain=v1"]]
    assert seen[0][-3:] == ["--", ".", ":!.beads/issues.jsonl"]
