"""Commit + push subprocess boundary between worker success and PR open.

`gh pr create` is not a substitute for `git push`. The orchestrator
needs a small adapter that owns the three git operations between
`run_worker` (when the worker's `.task_complete` sentinel shows up)
and `open_pr`:

- `status_is_dirty(worktree)` — any tracked-file changes?
- `commit_all(worktree, message) -> sha` — stage + commit, refusing
  empty commits; returns the new commit SHA.
- `push_branch(worktree, branch, remote="origin")` — first push with
  upstream-set so subsequent runs of `gh pr create` see the branch.

All git invocations pass `-C <worktree>` so the adapter is robust to
the caller's cwd, matching the pattern the `WorktreeManager` already
uses.

Credentials are the operator's responsibility (ssh-agent or
`gh auth`'s git credential helper). The adapter doesn't manage auth
and doesn't retry on transient push failures.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from turma.errors import PlanningError


GIT_INSTALL_HINT = (
    "git CLI not found. Install it (e.g. `brew install git` on macOS) "
    "and re-run."
)


COMMIT_MESSAGE_TEMPLATE = """\
[{turma_type}] {task_title}

Closes {task_id}.

Generated by turma run for feature "{feature}".\
"""


class GitAdapter:
    """Thin subprocess wrapper around `git -C <worktree> …`."""

    def __init__(self) -> None:
        if shutil.which("git") is None:
            raise PlanningError(GIT_INSTALL_HINT)

    def status_is_dirty(self, worktree: Path) -> bool:
        """True iff `git status --porcelain=v1` emits any tracked changes."""
        result = self._run(
            [
                "git", "-C", str(worktree),
                "status", "--porcelain=v1",
            ],
            step="git status",
        )
        return bool(result.stdout.strip())

    def commit_all(self, worktree: Path, message: str) -> str:
        """Stage everything, commit, and return the new commit SHA.

        Refuses to create an empty commit: if `status_is_dirty` is
        False at the start of the call, raises `PlanningError` with
        a fixed message the orchestrator converts into a worker-
        failure path ("worker reported success but left the tree
        clean").
        """
        if not self.status_is_dirty(worktree):
            raise PlanningError(
                "nothing to commit: worktree is clean. "
                "Did the worker actually modify any tracked files?"
            )

        self._run(
            ["git", "-C", str(worktree), "add", "-A"],
            step="git add",
        )
        self._run(
            ["git", "-C", str(worktree), "commit", "-m", message],
            step="git commit",
        )
        result = self._run(
            ["git", "-C", str(worktree), "rev-parse", "HEAD"],
            step="git rev-parse",
        )
        sha = result.stdout.strip()
        if not sha:
            raise PlanningError(
                "git rev-parse HEAD returned empty stdout"
            )
        return sha

    def push_branch(
        self,
        worktree: Path,
        branch: str,
        *,
        remote: str = "origin",
    ) -> None:
        """Push the task branch to `remote`, setting upstream on first push."""
        self._run(
            [
                "git", "-C", str(worktree),
                "push", "--set-upstream", remote, branch,
            ],
            step="git push",
        )

    def fetch_and_ff_base(
        self, repo_root: Path, base_branch: str
    ) -> None:
        """Fast-forward local `<base_branch>` from origin.

        Three argv calls in order:

            git -C <repo_root> symbolic-ref --short HEAD
            git -C <repo_root> fetch origin <base_branch>
            git -C <repo_root> merge --ff-only origin/<base_branch>

        The first call reads the current branch name. If it isn't
        `<base_branch>`, the method raises a typed PlanningError
        before any remote I/O — closing the silent-feature-FF
        footgun where `git merge --ff-only origin/<base_branch>`
        from a feature branch that's an ancestor of origin would
        silently advance the feature ref to origin's tip. The
        2026-04-26 chained-flow live smoke proved the prior
        single-call colon-form
        (`git fetch origin <base>:<base>`) was broken for the
        standard `turma run` usage (git refuses to fetch into a
        checked-out branch), and the design.md follow-up made the
        colon-form's "doesn't disturb HEAD" justification visibly
        wrong: git refused precisely because HEAD would be
        updated.

        See `openspec/changes/swarm-fetch-and-ff-base-correction/
        design.md` for the full rationale, including why the HEAD
        precheck was pulled into v1 scope rather than left as a
        documented precondition.

        Failure mapping:

        - `git symbolic-ref` returns a name that isn't
          `<base_branch>` → typed `PlanningError("HEAD is on
          <current>; turma run must run from a working copy with
          <base_branch> checked out. cd into the repo's
          <base_branch> checkout and re-run.")`. Fetch + merge
          NOT invoked.
        - `git symbolic-ref` non-zero (detached HEAD, etc.) →
          typed `PlanningError("HEAD is detached or unreadable:
          <stderr>; turma run requires <base_branch> checked
          out.")`. Fetch + merge NOT invoked.
        - `git fetch` non-zero → `PlanningError("git fetch
          failed: ...", stderr_preserved)`. Merge NOT invoked.
        - `git merge --ff-only` non-zero with stderr containing
          `Not possible to fast-forward` or `non-fast-forward`
          → typed divergence `PlanningError` naming the branch
          and pointing at the two `git log <a>..<b>` triage
          commands.
        - `git merge --ff-only` non-zero, other → `PlanningError(
          "git merge --ff-only failed: ...", stderr_preserved)`.
        """
        # 1. HEAD precheck — must be on <base_branch>.
        head_argv = [
            "git", "-C", str(repo_root),
            "symbolic-ref", "--short", "HEAD",
        ]
        head_result = subprocess.run(
            head_argv, capture_output=True, text=True
        )
        if head_result.returncode != 0:
            stderr = (head_result.stderr or "").strip() or "unknown error"
            raise PlanningError(
                f"HEAD is detached or unreadable: {stderr}; "
                f"turma run requires {base_branch} checked out."
            )
        current = (head_result.stdout or "").strip()
        if current != base_branch:
            raise PlanningError(
                f"HEAD is on {current}; turma run must run from a "
                f"working copy with {base_branch} checked out. "
                f"cd into the repo's {base_branch} checkout and "
                f"re-run."
            )

        # 2. Fetch origin/<base_branch>.
        fetch_argv = [
            "git", "-C", str(repo_root),
            "fetch", "origin", base_branch,
        ]
        fetch_result = subprocess.run(
            fetch_argv, capture_output=True, text=True
        )
        if fetch_result.returncode != 0:
            detail = (
                (fetch_result.stderr or "").strip()
                or (fetch_result.stdout or "").strip()
                or "unknown error"
            )
            raise PlanningError(
                f"git fetch failed: exit {fetch_result.returncode}\n{detail}"
            )

        # 3. Merge --ff-only origin/<base_branch>.
        merge_argv = [
            "git", "-C", str(repo_root),
            "merge", "--ff-only", f"origin/{base_branch}",
        ]
        merge_result = subprocess.run(
            merge_argv, capture_output=True, text=True
        )
        if merge_result.returncode == 0:
            return

        stderr = merge_result.stderr or ""
        if "Not possible to fast-forward" in stderr or "non-fast-forward" in stderr:
            raise PlanningError(
                f"local {base_branch} has diverged from "
                f"origin/{base_branch}; refusing to fast-forward. "
                f"Triage with `git log "
                f"{base_branch}..origin/{base_branch}` and "
                f"`git log origin/{base_branch}..{base_branch}` "
                f"to compare directions.\n{stderr.strip()}"
            )

        detail = (
            stderr.strip()
            or (merge_result.stdout or "").strip()
            or "unknown error"
        )
        raise PlanningError(
            f"git merge --ff-only failed: exit {merge_result.returncode}\n{detail}"
        )

    @staticmethod
    def _run(
        argv: list[str],
        *,
        step: str,
    ) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            argv,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            detail = (
                result.stderr.strip()
                or result.stdout.strip()
                or "unknown error"
            )
            raise PlanningError(
                f"{step} failed: exit {result.returncode}\n{detail}"
            )
        return result
