"""Commit + push subprocess boundary between worker success and PR open.

`gh pr create` is not a substitute for `git push`. The orchestrator
needs a small adapter that owns the three git operations between
`run_worker` (when the worker's `.task_complete` sentinel shows up)
and `open_pr`:

- `status_is_dirty(worktree)` — any tracked-file changes?
- `commit_all(worktree, message) -> sha` — stage + commit, refusing
  empty commits; returns the new commit SHA.
- `push_branch(worktree, branch, remote="origin")` — first push with
  upstream-set so subsequent runs of `gh pr create` see the branch.

All git invocations pass `-C <worktree>` so the adapter is robust to
the caller's cwd, matching the pattern the `WorktreeManager` already
uses.

Credentials are the operator's responsibility (ssh-agent or
`gh auth`'s git credential helper). The adapter doesn't manage auth
and doesn't retry on transient push failures.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from turma.errors import PlanningError


GIT_INSTALL_HINT = (
    "git CLI not found. Install it (e.g. `brew install git` on macOS) "
    "and re-run."
)


COMMIT_MESSAGE_TEMPLATE = """\
[{turma_type}] {task_title}

Closes {task_id}.

Generated by turma run for feature "{feature}".\
"""


class GitAdapter:
    """Thin subprocess wrapper around `git -C <worktree> …`."""

    def __init__(self) -> None:
        if shutil.which("git") is None:
            raise PlanningError(GIT_INSTALL_HINT)

    def status_is_dirty(
        self, worktree: Path, *, ignore_bd_export: bool = False
    ) -> bool:
        """True iff `git status --porcelain=v1` emits any tracked changes.

        With ``ignore_bd_export=True`` the bd export (`.beads/issues.jsonl`) is
        excluded — matching exactly what `commit_worker_changes` stages — so
        "did the worker leave real changes?" is decided on the same set that
        would actually be committed. Without the exclusion, a stray bd rewrite
        of the export could make an otherwise-clean worktree look dirty and the
        code-only commit would then find nothing to stage.
        """
        argv = ["git", "-C", str(worktree), "status", "--porcelain=v1"]
        if ignore_bd_export:
            argv += ["--", ".", ":!.beads/issues.jsonl"]
        result = self._run(argv, step="git status")
        return bool(result.stdout.strip())

    def commit_all(self, worktree: Path, message: str) -> str:
        """Stage everything, commit, and return the new commit SHA.

        Refuses to create an empty commit: if `status_is_dirty` is
        False at the start of the call, raises `PlanningError` with
        a fixed message the orchestrator converts into a worker-
        failure path ("worker reported success but left the tree
        clean").
        """
        if not self.status_is_dirty(worktree):
            raise PlanningError(
                "nothing to commit: worktree is clean. "
                "Did the worker actually modify any tracked files?"
            )

        self._run(
            ["git", "-C", str(worktree), "add", "-A"],
            step="git add",
        )
        self._run(
            ["git", "-C", str(worktree), "commit", "-m", message],
            step="git commit",
        )
        result = self._run(
            ["git", "-C", str(worktree), "rev-parse", "HEAD"],
            step="git rev-parse",
        )
        sha = result.stdout.strip()
        if not sha:
            raise PlanningError(
                "git rev-parse HEAD returned empty stdout"
            )
        return sha

    def commit_worker_changes(
        self,
        worktree: Path,
        message: str,
    ) -> str:
        """Commit the worker's changes on a task branch — **code only**.

        Four steps:

        1. `git status --porcelain=v1` empty-commit guard (excluding the bd
           export) — refuse if the worker left the tree clean.
        2. `git -C <worktree> add -A` — stage the worker's file changes.
        3. `git -C <worktree> reset -q -- .beads/issues.jsonl` — unstage the bd
           export. A `git add` pathspec exclude only controls what `add`
           *stages*; it cannot un-stage a `.beads/issues.jsonl` that bd already
           staged (bd's `export.git-add=true` default). `git reset` on the path
           drops it from the index regardless of how it got staged (modified,
           deleted, added), and — unlike `git restore --staged` — is a clean
           no-op (exit 0) when the export is untracked and unstaged, which is
           reachable here since task commits never track it (bd only writes the
           export on a bd write/export).
        4. `git -C <worktree> -c core.hooksPath=/dev/null commit -m <message>`.

        Task commits must not carry `.beads/issues.jsonl`. That file is a
        derived snapshot of shared bd state; committing it on every task branch
        made sibling PRs (opened off the same base before any merged) conflict on
        it (see `openspec/changes/swarm-bd-export-serialization/`). bd state
        propagates on its own via bd's Dolt-over-git auto-sync, so Turma neither
        exports into the worktree nor commits the export here.

        The `core.hooksPath=/dev/null` bypass is **load-bearing** and must stay:
        it stops bd's pre-commit hook from re-exporting and re-staging
        `.beads/issues.jsonl` into this commit (and still sidesteps the bd
        wrong-path hook bug). Removing it re-introduces the export on the branch.

        Returns the new commit SHA via a final `rev-parse HEAD`.

        Failure-boundary contract: any step raising means zero git mutations
        occur after the failing step — no partial-commit intermediate state.
        """
        if not self.status_is_dirty(worktree, ignore_bd_export=True):
            raise PlanningError(
                "nothing to commit: worktree is clean. "
                "Did the worker actually modify any tracked files?"
            )

        self._run(
            ["git", "-C", str(worktree), "add", "-A"],
            step="git add",
        )
        # Unstage the bd export in case bd already staged it — the exclusion
        # must be an un-stage, not just an add-time filter (see docstring).
        # `git reset` (not `restore --staged`): a clean no-op when the export is
        # untracked, which is reachable since task commits never track it.
        self._run(
            [
                "git", "-C", str(worktree),
                "reset", "-q", "--", ".beads/issues.jsonl",
            ],
            step="git reset",
        )
        self._run(
            [
                "git", "-C", str(worktree),
                "-c", "core.hooksPath=/dev/null",
                "commit", "-m", message,
            ],
            step="git commit",
        )
        result = self._run(
            ["git", "-C", str(worktree), "rev-parse", "HEAD"],
            step="git rev-parse",
        )
        sha = result.stdout.strip()
        if not sha:
            raise PlanningError(
                "git rev-parse HEAD returned empty stdout"
            )
        return sha

    def push_branch(
        self,
        worktree: Path,
        branch: str,
        *,
        remote: str = "origin",
    ) -> None:
        """Push the task branch to `remote`, setting upstream on first push."""
        self._run(
            [
                "git", "-C", str(worktree),
                "push", "--set-upstream", remote, branch,
            ],
            step="git push",
        )

    def fetch_and_ff_base(
        self, repo_root: Path, base_branch: str
    ) -> None:
        """Fast-forward local `<base_branch>` from origin.

        Three argv calls in order:

            git -C <repo_root> symbolic-ref --short HEAD
            git -C <repo_root> fetch origin <base_branch>
            git -C <repo_root> merge --ff-only origin/<base_branch>

        The first call reads the current branch name. If it isn't
        `<base_branch>`, the method raises a typed PlanningError
        before any remote I/O — closing the silent-feature-FF
        footgun where `git merge --ff-only origin/<base_branch>`
        from a feature branch that's an ancestor of origin would
        silently advance the feature ref to origin's tip. The
        2026-04-26 chained-flow live smoke proved the prior
        single-call colon-form
        (`git fetch origin <base>:<base>`) was broken for the
        standard `turma run` usage (git refuses to fetch into a
        checked-out branch), and the design.md follow-up made the
        colon-form's "doesn't disturb HEAD" justification visibly
        wrong: git refused precisely because HEAD would be
        updated.

        See `openspec/changes/swarm-fetch-and-ff-base-correction/
        design.md` for the full rationale, including why the HEAD
        precheck was pulled into v1 scope rather than left as a
        documented precondition.

        Failure mapping:

        - `git symbolic-ref` returns a name that isn't
          `<base_branch>` → typed `PlanningError("HEAD is on
          <current>; turma run must run from a working copy with
          <base_branch> checked out. cd into the repo's
          <base_branch> checkout and re-run.")`. Fetch + merge
          NOT invoked.
        - `git symbolic-ref` non-zero (detached HEAD, etc.) →
          typed `PlanningError("HEAD is detached or unreadable:
          <stderr>; turma run requires <base_branch> checked
          out.")`. Fetch + merge NOT invoked.
        - `git fetch` non-zero → `PlanningError("git fetch
          failed: ...", stderr_preserved)`. Merge NOT invoked.
        - `git merge --ff-only` non-zero with stderr containing
          `Not possible to fast-forward` or `non-fast-forward`
          → typed divergence `PlanningError` naming the branch
          and pointing at the two `git log <a>..<b>` triage
          commands.
        - `git merge --ff-only` non-zero, other → `PlanningError(
          "git merge --ff-only failed: ...", stderr_preserved)`.
        """
        # 1. HEAD precheck — must be on <base_branch>.
        head_argv = [
            "git", "-C", str(repo_root),
            "symbolic-ref", "--short", "HEAD",
        ]
        head_result = subprocess.run(
            head_argv, capture_output=True, text=True
        )
        if head_result.returncode != 0:
            stderr = (head_result.stderr or "").strip() or "unknown error"
            raise PlanningError(
                f"HEAD is detached or unreadable: {stderr}; "
                f"turma run requires {base_branch} checked out."
            )
        current = (head_result.stdout or "").strip()
        if current != base_branch:
            raise PlanningError(
                f"HEAD is on {current}; turma run must run from a "
                f"working copy with {base_branch} checked out. "
                f"cd into the repo's {base_branch} checkout and "
                f"re-run."
            )

        # 2. Fetch origin/<base_branch>.
        fetch_argv = [
            "git", "-C", str(repo_root),
            "fetch", "origin", base_branch,
        ]
        fetch_result = subprocess.run(
            fetch_argv, capture_output=True, text=True
        )
        if fetch_result.returncode != 0:
            detail = (
                (fetch_result.stderr or "").strip()
                or (fetch_result.stdout or "").strip()
                or "unknown error"
            )
            raise PlanningError(
                f"git fetch failed: exit {fetch_result.returncode}\n{detail}"
            )

        # 3. Merge --ff-only origin/<base_branch>.
        merge_argv = [
            "git", "-C", str(repo_root),
            "merge", "--ff-only", f"origin/{base_branch}",
        ]
        merge_result = subprocess.run(
            merge_argv, capture_output=True, text=True
        )
        if merge_result.returncode == 0:
            return

        stderr = merge_result.stderr or ""
        if "Not possible to fast-forward" in stderr or "non-fast-forward" in stderr:
            raise PlanningError(
                f"local {base_branch} has diverged from "
                f"origin/{base_branch}; refusing to fast-forward. "
                f"Triage with `git log "
                f"{base_branch}..origin/{base_branch}` and "
                f"`git log origin/{base_branch}..{base_branch}` "
                f"to compare directions.\n{stderr.strip()}"
            )

        detail = (
            stderr.strip()
            or (merge_result.stdout or "").strip()
            or "unknown error"
        )
        raise PlanningError(
            f"git merge --ff-only failed: exit {merge_result.returncode}\n{detail}"
        )

    def revert_paths(
        self, repo_root: Path, paths: tuple[str, ...]
    ) -> None:
        """Restore `paths` in `repo_root`'s working tree AND
        index to the HEAD version, discarding both staged and
        unstaged changes.

        argv: `git -C <repo_root> restore --staged --worktree
              -- <p1> <p2> ...`.

        Both `--staged` and `--worktree` are required because
        bd's `export.git-add=true` (default) means `bd update`
        writes AND stages `.beads/issues.jsonl`. A simple
        `git checkout -- <path>` would only fix the worktree;
        the index would still be dirty and the next
        `merge --ff-only` would still refuse.

        Empty paths tuple → no subprocess call, returns None
        immediately. Don't fire git with zero paths (its
        defaults are surprising).

        Failure surfaces as `PlanningError("git restore
        failed: ...")` with stderr preserved.

        See `openspec/changes/swarm-beads-state-merge-cleanliness/
        design.md` "Adapter contract" for the rationale.
        """
        if not paths:
            return
        argv = [
            "git", "-C", str(repo_root),
            "restore", "--staged", "--worktree",
            "--", *paths,
        ]
        result = subprocess.run(argv, capture_output=True, text=True)
        if result.returncode == 0:
            return
        detail = (
            (result.stderr or "").strip()
            or (result.stdout or "").strip()
            or "unknown error"
        )
        raise PlanningError(
            f"git restore failed: exit {result.returncode}\n{detail}"
        )

    def path_is_dirty(self, repo_root: Path, path: str) -> bool:
        """True if `path` has tracked-file modifications
        (staged, unstaged, or both) in `repo_root`'s working
        tree.

        argv: `git -C <repo_root> status --porcelain=v1
              -- <path>`.

        Returns False if the path is clean OR present only
        as untracked (`??`-prefixed lines). Untracked files
        at the path are the operator's business, not Turma's
        — we don't refuse to start on them.

        Failure surfaces as `PlanningError("git status
        failed: ...")` with stderr preserved, rather than
        being silently treated as clean.

        Used by the preflight check at the top of
        `run_swarm` to refuse on a pre-existing dirty
        `.beads/issues.jsonl`.
        """
        argv = [
            "git", "-C", str(repo_root),
            "status", "--porcelain=v1", "--", path,
        ]
        result = subprocess.run(argv, capture_output=True, text=True)
        if result.returncode != 0:
            detail = (
                (result.stderr or "").strip()
                or (result.stdout or "").strip()
                or "unknown error"
            )
            raise PlanningError(
                f"git status failed: exit {result.returncode}\n{detail}"
            )
        for line in (result.stdout or "").splitlines():
            if not line:
                continue
            if line.startswith("??"):
                continue
            return True
        return False

    @staticmethod
    def _run(
        argv: list[str],
        *,
        step: str,
    ) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            argv,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            detail = (
                result.stderr.strip()
                or result.stdout.strip()
                or "unknown error"
            )
            raise PlanningError(
                f"{step} failed: exit {result.returncode}\n{detail}"
            )
        return result
